//  Copyright (c) 2022 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:projectid: grpc-intro
:page-layout: guide-multipane
:page-duration: 30 minutes
:page-releasedate: 2022-07-08
:page-guide-category: none
:page-essential: false
:page-description: Learn how to use gRPC to send properties through a traditional REST, along with server, client, and bidirectional streaming using Open Liberty.
:guide-author: Open Liberty
:page-tags: ['gRPC']
:page-related-guides: []
:page-permalink: /guides/{projectid}
:imagesdir: /img/guide/{projectid}
:page-seo-title: Streaming updates from a MicroProfile Reactive Messaging microservice using Server-Sent Events (SSE)
:page-seo-description: A getting started tutorial with examples on how to run unary, server streaming, client streaming, and bi-directional streaming various properties using gRPC calls.
:common-includes: https://raw.githubusercontent.com/OpenLiberty/guides-common/prod
:source-highlighter: prettify

= Exchanging system properties between client and a server using gRPC

[.hidden]
NOTE: This repository contains the guide documentation source. To view the guide in published form, view it on the https://openliberty.io/guides/{projectid}.html[Open Liberty website].

Learn how to make gRPC service calls in traditional REST fashion along with streaming. 

// =================================================================================================
//  What you'll learn
// =================================================================================================

== What you'll learn

You will learn how to create various types of gRPC services using protocol buffers and how to implement them using Open Liberty. You will use Maven throughout the guide to generate the gRPC stubs and deploy the microservice as well as to interact with the running Liberty instance. 

=== What is gRPC?
gRPC is a technology that implements RPC style APIs using HTTP/2.
Remote Procedure Call (RPC) is a protocol that provides the high-level communications paradigm used in the operating system. The RPC protocol enables users to work with remote procedures as if the procedures were local. The remote procedure calls are defined through routines contained in the RPC protocol. As the routines are predefined, the RPC calls are lightweight and straightforward. 

gRPC uses Protocol Buffers to define its routines which include service calls as well as expected messages. For each service defined in the .proto file, gRPC will automatically generate the skeleton code for users to implement/ extend. Protocol Buffers uses a binary format to send and receive messages which end up being much faster and lightweight compared to JSON used in traditional REST APIs.

gRPC clients and servers are also able to run and communicate with each other even if they are not on the same environments, as long as the .proto file is defined and the stubs are generated. For example, an gRPC client is able to make a call to a gRPC server running on a different machine. This allows for an easy integration microservices. 

The application you will build in this guide consists of a `query` serice, a `system` service, and a `systemproto` service.


// =================================================================================================
// Getting Started
// =================================================================================================
[role='command']
include::{common-includes}/gitclone.adoc[]

=== Try what you'll build
The `finish` directory in the root of this guide contains the finished application. Give it a try before you proceed.

To try out the application, first go to the `finish` directory and run the following Maven goal to generate all the gRPC abstract classes defined in the proto file. 

// generate gRPC classes
[role='command']
----
cd finish
mvn -pl systemproto install
----

Start the system service by running the following maven command. 
// starting system
[role='command']
----
mvn -pl system liberty:dev
----

Next, open another terminal window and run the following maven command to start the query service.  
// starting query
[role='command']
----
mvn -pl query liberty:dev
----

Open another terminal window and run the following curl command to test out the basic unary service. Replace `<propertiesName>` with the name of the property you would like to see, an example is `os.name`. You should see your system os name in the terminal. 
// curl request to test endpoint
[role='command']
----
curl http://localhost:9081/query/properties/<propertiesName>
----

After you're statisfied testing the unary service, close the query and system servers using the instructions below or by pressing `q` or `CTRL + C`.
// stopping dev mode
[role='command']
----
mvn -pl system liberty:stop
mvn -pl query liberty:stop
----

== Creating and defining gRPC services

// go to start directory
[role='command']
----
cd ../start
----

// Create SystemProto.proto
[role="code_command hotspot file=0", subs="quotes"]
----
#Create the `SystemProto` class.#
`finish/systemproto/src/main/proto/SystemService.proto`
----
SystemProto.java
[source, Java, linenums, indent=0, role="code_column hide_tags=copyright"]
----
link:finish/system/src/main/java/io/openliberty/guides/system/SystemProto.java[]
----

SystemProto defines

// run mvn install to generate abstract classes
[role='command']
----
mvn -pl systeproto install
----

== Implementing unary call

// Commands for system service
// start dev mode for system
[role='command']
```
mvn -pl system liberty:dev
```

// Create SystemService
[role="code_command hotspot file=0", subs="quotes"]
----
#Create the `SystemService` class.#
`/system/src/main/java/io/openliberty/guides/system/SystemService.java`
----

SystemService.java
[source, Java, linenums, indent=0, role="code_column hide_tags=copyright"]
----
link:finish/system/src/main/java/io/openliberty/guides/system/SystemService.java[]
----

// update server.xml
[role='code_command hotspot file=1', subs="quotes"]
----
#Replace the `server.xml` file.#
`src/main/liberty/config/server.xml`
----

server.xml
[source, xml, linenums, role='code_column hide_tags=copyright']
----
include::finish/system/src/main/liberty/config/server.xml[]
----

// Commands for query service
// start dev mode for query
[role='command']
```
mvn -pl query liberty:dev
```

// Create PropertiesResource
[role="code_command hotspot file=2", subs="quotes"]
----
#Create the `PropertiesResource` class.#
`/query/src/main/java/io/openliberty/guides/query/PropertiesResource.java`
----

PropertiesResource.java
[source, Java, linenums, indent=0, role="code_column hide_tags=copyright"]
----
link:finish/query/src/main/java/io/openliberty/guides/query/PropertiesResource.java[]
----

// update server.xml
[role='code_command hotspot file=3', subs="quotes"]
----
#Replace the `server.xml` file.#
`src/main/liberty/config/server.xml`
----

server.xml
[source, xml, linenums, role='code_column hide_tags=copyright']
----
include::finish/query/src/main/liberty/config/server.xml[]
----

// curl request
[role='command']
----
curl http://localhost:9081/query/properties/<propertiesName>
----

== Implementing server streaming 

// Commands for system service
// Replace SystemService
[role="code_command hotspot file=0", subs="quotes"]
----
#Replace the `SystemService` class.#
`/system/src/main/java/io/openliberty/guides/system/SystemService.java`
----

SystemService.java
[source, Java, linenums, indent=0, role="code_column hide_tags=copyright"]
----
link:finish/system/src/main/java/io/openliberty/guides/system/SystemService.java[]
----

// Commands for query service

// Replace PropertiesResource
[role="code_command hotspot file=2", subs="quotes"]
----
#Replace the `PropertiesResource` class.#
`/query/src/main/java/io/openliberty/guides/query/PropertiesResource.java`
----

PropertiesResource.java
[source, Java, linenums, indent=0, role="code_column hide_tags=copyright"]
----
link:finish/query/src/main/java/io/openliberty/guides/query/PropertiesResource.java[]
----

// curl request
[role='command']
----
curl http://localhost:9081/query/properties/os
----


== Implementing client streaming 

// Commands for system service
// Replace SystemService
[role="code_command hotspot file=0", subs="quotes"]
----
#Replace the `SystemService` class.#
`/system/src/main/java/io/openliberty/guides/system/SystemService.java`
----

SystemService.java
[source, Java, linenums, indent=0, role="code_column hide_tags=copyright"]
----
link:finish/system/src/main/java/io/openliberty/guides/system/SystemService.java[]
----

// Commands for query service

// Replace PropertiesResource
[role="code_command hotspot file=2", subs="quotes"]
----
#Replace the `PropertiesResource` class.#
`/query/src/main/java/io/openliberty/guides/query/PropertiesResource.java`
----

PropertiesResource.java
[source, Java, linenums, indent=0, role="code_column hide_tags=copyright"]
----
link:finish/query/src/main/java/io/openliberty/guides/query/PropertiesResource.java[]
----

// curl request
[role='command']
----
curl http://localhost:9081/query/properties/user
----

== Implementing bidirectional streaming 

// Commands for system service
// Replace SystemService
[role="code_command hotspot file=0", subs="quotes"]
----
#Replace the `SystemService` class.#
`/system/src/main/java/io/openliberty/guides/system/SystemService.java`
----

SystemService.java
[source, Java, linenums, indent=0, role="code_column hide_tags=copyright"]
----
link:finish/system/src/main/java/io/openliberty/guides/system/SystemService.java[]
----

// Commands for query service

// Replace PropertiesResource
[role="code_command hotspot file=2", subs="quotes"]
----
#Replace the `PropertiesResource` class.#
`/query/src/main/java/io/openliberty/guides/query/PropertiesResource.java`
----

PropertiesResource.java
[source, Java, linenums, indent=0, role="code_column hide_tags=copyright"]
----
link:finish/query/src/main/java/io/openliberty/guides/query/PropertiesResource.java[]
----

// curl request
[role='command']
----
curl http://localhost:9081/query/properties/java
----

== Testing the application
// Create QueryIT.java
[role="code_command hotspot file=0", subs="quotes"]
----
#Create the `QueryIT` class.#
`finish/query/src/main// #TODO`
----
QueryIT.java
[source, Java, linenums, indent=0, role="code_column hide_tags=copyright"]
----
link:finish/query/#TODO
----

[role="code_command hotspot", subs="quotes"]
----
#Create the `QueryIT` class.#
`finish/src/test/java/it/io/openliberty/guides/QueryIT.java`
----

QueryIT.java
[source, Java, linenums, indent=0, role="code_column hide_tags=copyright"]
----
link:finish/query/src/test/java/it/io/openliberty/guides/QueryIT.java[]
----

[role='command']
link:https://raw.githubusercontent.com/OpenLiberty/guides-common/master/devmode-test.adoc[]

[role='command']
link:https://raw.githubusercontent.com/OpenLiberty/guides-common/master/devmode-quit.adoc[]


== Great work! You're done!
[role='command']
link:https://raw.githubusercontent.com/OpenLiberty/guides-common/master/attribution.adoc[]